language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t carrola7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true carrola7/docker-react npm run test
